### ISSUE TITLE
vengeful mob issue

### ISSUE THREAD

**Issue by gravysauce481** [MelnCat/melncat.github.io#1]
Hello, I don't know how to contact you any other way, but I have a problem with your vengeful mobs plugin on Modrinth: I can't manually set the attack damage from the config amount for a mob. For example, dolphins can only do 3 damage. Every dolphin is that way. Giving them items with attribute modifiers doesn't work, changing the actual attribute has no effect; seems that on spawn the attribute gets sets by the plugin to the config value. So if you still want to develop this plugin, please consider this change. Everything else is fine, even new mobs work. But the damage override via attributes would be nice, or at the very least allowing items with attribute modifiers to work. Sorry for weird way to contact you lol, would be nice if I could put a comment on the mod page but yeah

**Comment by MelnCat** [comment]
I see, I'll look into it.
